version: '3.8'
services:
  proxy:
    image: upgrade-nginx:TAG
    restart: always
    ports:
      - '5000:5000'
      - '443:443'
      - '80:80'
    deploy:
      replicas: 1
    depends_on:
      - upgrade
      #command: ["/wait-for-it.sh", "http://upgrade:5454/", "--", "nginx", "-g", "daemon off;"]
  upgrade:
    restart: always
    image: upgrade:TAG
    deploy:
      replicas: 1
