version: '3.8'
services:
  proxy:
    image: upgrade-nginx:TAG
    restart: always
    ports:
      - '443:443'
      - '80:80'
    deploy:
      replicas: 1
    depends_on:
      - upgrade
  upgrade:
    restart: always
    image: upgrade:TAG
    deploy:
      replicas: 1
